// Runs an orchestration graph as a Claude Code workflow: one session whose Workflow tool drives
// every task as a subagent. The script is generated from the graph, never written by a model, so
// what runs is exactly what the draft showed: the same prompts the graph engine's workers get, the
// same dependencies, the same concurrency and the same synthesis.

export interface CompiledTask {
  id: string;
  name: string;
  dependsOn: string[];
  model?: string;
  /** Prompt text that goes before the dependencies' results */
  before: string;
  /** Prompt text that goes after them: the task itself */
  after: string;
}

export interface CompileInput {
  name: string;
  description: string;
  concurrency: number;
  tasks: CompiledTask[];
  /** Opening of the synthesis prompt; the tasks' results follow it. Null skips the synthesis. */
  synthesis: string | null;
  /** How much of a dependency's result is passed on */
  maxContext: number;
}

/** What the script returns, and so what the CLI records as the workflow's result. */
export interface CompiledResult {
  results: Record<string, string | null>;
  skipped: string[];
  synthesis: string | null;
}

/** Workflow names are file names too: lower case, digits and dashes. */
export function workflowName(name: string): string {
  const slug = name
    .normalize('NFKD')
    // NFKD splits an accented letter into the letter and its mark; the mark goes
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);
  return `agentry-${slug || 'orchestration'}`;
}

// The runtime part is plain JavaScript for the CLI's workflow sandbox: no TypeScript, no
// template literals (it is embedded in one here), and none of Date.now()/Math.random(), which the
// sandbox rejects because they would break a resume.
const RUNTIME = String.raw`
let active = 0
const waiting = []
async function slot(work) {
  if (active >= LIMIT) await new Promise((resolve) => waiting.push(resolve))
  else active++
  try {
    return await work()
  } finally {
    const next = waiting.shift()
    if (next) next()
    else active--
  }
}

const byId = Object.fromEntries(TASKS.map((t) => [t.id, t]))
const started = {}
const skipped = []

// Each task waits only for its own dependencies: nothing is held back by an unrelated slow one
function run(task) {
  if (!started[task.id]) {
    started[task.id] = (async () => {
      const deps = await Promise.all(task.dependsOn.map((id) => run(byId[id])))
      if (deps.some((d) => d === null)) {
        skipped.push(task.id)
        return null
      }
      const context = task.dependsOn.length
        ? 'Results from the tasks you depend on:\n' +
          task.dependsOn
            .map((id, i) => '<task id="' + id + '" name="' + byId[id].name + '">\n' + String(deps[i]).slice(0, MAX_CONTEXT) + '\n</task>')
            .join('\n')
        : ''
      const prompt = [task.before, context, task.after].filter(Boolean).join('\n\n')
      const opts = { label: task.id, phase: 'Tasks' }
      if (task.model) opts.model = task.model
      const result = await slot(() => agent(prompt, opts))
      if (result === null || result === undefined) return null
      return typeof result === 'string' ? result : JSON.stringify(result)
    })()
  }
  return started[task.id]
}

const results = await Promise.all(TASKS.map(run))
const byTask = Object.fromEntries(TASKS.map((t, i) => [t.id, results[i]]))

let synthesis = null
if (SYNTHESIS !== null && results.some((r) => r !== null)) {
  const reports = TASKS.map((t, i) => {
    const status = results[i] !== null ? 'completed' : skipped.includes(t.id) ? 'skipped' : 'failed'
    return '<task id="' + t.id + '" name="' + t.name + '" status="' + status + '">\n' + String(results[i] ?? '').slice(0, MAX_CONTEXT) + '\n</task>'
  })
  synthesis = await agent(SYNTHESIS + '\n\n' + reports.join('\n'), { label: 'synthesis', phase: 'Synthesis' })
}

return { results: byTask, skipped, synthesis }
`;

export function compileWorkflow(input: CompileInput): string {
  const phases = [{ title: 'Tasks' }, ...(input.synthesis !== null ? [{ title: 'Synthesis' }] : [])];
  // JSON is a valid JavaScript literal, and `meta` has to be one
  const tasks = input.tasks.map((t) => ({ id: t.id, name: t.name, dependsOn: t.dependsOn, ...(t.model ? { model: t.model } : {}), before: t.before, after: t.after }));
  return [
    '// Generated by Agentry from an orchestration graph. Editing it here changes nothing: Agentry',
    '// regenerates it from the graph. Save it as a project workflow to keep and edit a copy.',
    'export const meta = {',
    `  name: ${JSON.stringify(workflowName(input.name))},`,
    `  description: ${JSON.stringify(input.description.slice(0, 200) || input.name)},`,
    `  phases: ${JSON.stringify(phases)},`,
    '}',
    '',
    `const TASKS = ${JSON.stringify(tasks, null, 2)}`,
    `const SYNTHESIS = ${JSON.stringify(input.synthesis)}`,
    `const LIMIT = ${Math.max(1, Math.floor(input.concurrency))}`,
    `const MAX_CONTEXT = ${Math.max(1, Math.floor(input.maxContext))}`,
    RUNTIME,
  ].join('\n');
}

/** The result the script returned, when it is the shape it returns. */
export function readCompiledResult(value: unknown): CompiledResult | null {
  if (!value || typeof value !== 'object') return null;
  const o = value as Record<string, unknown>;
  if (!o.results || typeof o.results !== 'object') return null;
  const results: Record<string, string | null> = {};
  for (const [id, r] of Object.entries(o.results as Record<string, unknown>)) results[id] = typeof r === 'string' ? r : null;
  return {
    results,
    skipped: Array.isArray(o.skipped) ? o.skipped.filter((s): s is string => typeof s === 'string') : [],
    synthesis: typeof o.synthesis === 'string' ? o.synthesis : null,
  };
}
